### ISSUE TITLE
Always get a 1kb image file on M1 MacOS

### ISSUE THREAD

**Issue by shenlebantongying** [finalpatch/ob-glsl#1]
I successfully built the module and loaded it to emacs by 
```lisp
(add-to-list 'load-path "~/.emacs.d/lisp")

(org-babel-do-load-languages
 'org-babel-load-languages
 '((glsl . t)))
```

However, I always get no result, the .png file is always an empty 1 Kb image only.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/20123683/135999043-f7980e7d-247f-45be-a687-e31c138d194f.png">

When compiling the module, I get this warning:

```
[3/4] Building CXX object CMakeFiles/ob-glsl-module.dir/Main.cpp.o
Main.cpp:86:40: warning: implicit conversion of nullptr constant to 'bool' [-Wnull-conversion]
        glbinding::Binding::initialize(nullptr);
        ~~~~~~~~~                      ^~~~~~~
                                       false
1 warning generated.
[4/4] Linking CXX shared library ob-glsl-module.dylib
```

Maybe this is the reason?

I have very limited knowledge both Emacs modules in C or openGL, and I am not sure about how to debug in this situation. Sorry for that.

Also, the glbinding from my package manager is still 2.1.4.

**Comment by finalpatch** [comment]
tried on my intel mac, doesn't work either, got empty image

**Comment by finalpatch** [comment]
thanks for reporting this

**Comment by finalpatch** [comment]
apparently glreadpixels from a hidden window does not work on macos. i'll have to try a different technique.

**Comment by finalpatch** [comment]
pushed a fix to master. works on my intel mac now.

**Comment by shenlebantongying** [comment]
Fabulous!
